### ISSUE TITLE
Threshold for input normals

### ISSUE THREAD

**Issue by eyegotthis** [woodfrog/heat#10]
Hi there, 
Thank you very much for sharing your work. It is amazing! 

I was going through the inference script and i noticed that you use normals along with the density maps and these normals are either [0,255]. However, the normals calculated during data generation are between 0 and 255. May I know what threshold (between 0 and 255) you used to get the normal maps for your inputs? It would be really nice if I get an idea here. Looking forward to your response!

**Comment by woodfrog** [comment]
Hi, thank you for your interest. 

The data preprocessing for the floorplan reconstruction task is documented [here](https://github.com/woodfrog/heat/tree/master/s3d_preprocess), and I think [this function](https://github.com/woodfrog/heat/blob/b7213df64621359896fd94bad284a437a3981181/s3d_preprocess/DataProcessing/FloorRW.py#L62) is what you are looking for, and the generated normals are saved by [this function](https://github.com/woodfrog/heat/blob/b7213df64621359896fd94bad284a437a3981181/s3d_preprocess/DataProcessing/FloorRW.py#L189).

**Comment by eyegotthis** [comment]
Thanks for the response! 
The function you mentioned seems to be saving values between [0,255]. However, the normals fed into the network have either 0 or 255. For this reason I was wondering what function could have been used to decide what is 0 and whats 255. Couldnt find it so far :confounded:

**Comment by woodfrog** [comment]
> Thanks for the response! The function you mentioned seems to be saving values between [0,255]. However, the normals fed into the network have either 0 or 255. For this reason I was wondering what function could have been used to decide what is 0 and whats 255. Couldnt find it so far 😖

Thanks for clarifying. I now understand the question. I guess the issue is here: [this line]()https://github.com/woodfrog/heat/blob/b7213df64621359896fd94bad284a437a3981181/s3d_preprocess/DataProcessing/PointCloudReaderPanorama.py#L175 and [this line]()https://github.com/woodfrog/heat/blob/b7213df64621359896fd94bad284a437a3981181/s3d_preprocess/DataProcessing/FloorRW.py#L191 did the range conversion twice, thus losing all intermediate values. This is a bug in the preprocessing script. However, I borrowed this preprocessing part from MonteFloor and kept everything unchanged to make sure the inputs (i.e., density and normal) were the same. If you are running the preprocessing on your own data, you could fix this bug to produce the correct normal values.

**Comment by eyegotthis** [comment]
Everything makes sense now, thanks for clarifying!
