### ISSUE TITLE
Ground truth of Structured3D

### ISSUE THREAD

**Issue by ywyue** [woodfrog/heat#3]
Hi, Thanks for your great work! I have a question regarding the ground truth of Structured3D floorplan. For quantitative evaluation of floorplan reconstruction, it is mentioned that you also used the data used by MonteFloor (downloaded from [here](https://drive.google.com/file/d/1XpKm3vjvw4lOw32pX81w0U0YL_PBuzez/view?usp=sharing)). I downloaded the data and found the ground truth corner is actually preprocessed. Below is a comparison (scene_00030) between the GT label you used and the GT I generated from Structured3D annotations. It shows that in the GT label you used, corners and edges of adjacent rooms are merged. Could you please explain how the adjacent rooms are merged? Another thing is that it seems that the GT label has been re-annotated (see bottom right). Could you please also explain this? It would be great if you can provide the preprocessing script. Thanks in advance!

![GT_stru3d](https://user-images.githubusercontent.com/40747438/177218233-4c866a11-afd0-4e02-9740-f74fb022e3d8.png)

**Comment by woodfrog** [comment]
Thanks for your interest! Please check the recent commits for the preprocessing scripts of Structured3D floorplan data. 

The raw Structured3D annotations are merged to generate the "training G.T." for HEAT because we consider each floorplan as a planar graph instead of a list of closed polygons. However, note that these "processed annotations" (your left figure) are only used for training. For evaluation, we extract the room polygons from the estimated planar graph of HEAT and use the raw Structured3D annotations (your right figure) as the ground truth for quantitative evaluation. Hope this clarifies.

**Comment by ywyue** [comment]
Thanks for the reply! (Sorry I forgot to close this issue after our email communication) Close now.
