### ISSUE TITLE
Usage of Normals

### ISSUE THREAD

**Issue by coldmanck** [woodfrog/heat#5]
Hi @woodfrog thank you for the great work! I think one missing point of this codebase is that what's the intuition behind the usage of normals, which is not discussed in paper or in this codebase. What's your idea of incorporating normals into density maps as the input to HEAT? Is there any reference?

I'd also like to have you clarify some details in your codebase. Especially, for the below two snippets:
https://github.com/woodfrog/heat/blob/c73a690b8f526bb0a7b3a6be89c6bdcc7a98a34d/s3d_preprocess/DataProcessing/PointCloudReaderPanorama.py#L163-L175
- Why `normals[::10]` here? I guess it's kind of a sampling operation on the dense point cloud. How did you decide this hyperparameter `10 `? I personally found that a lower number such as `5` works better for my data.
- For L175, it clip the normal values into [0, 1] followed by transform into [0, 255]. However, the original normal values are [-1, 1]. Why do you ignore the negative normal values?

https://github.com/woodfrog/heat/blob/66aca88896187e7c2abdc91097730f02ab3b1839/datasets/s3d_floorplans.py#L51
- Density input is a 3-channel copy of a single 256x256x1 array. I wonder what's the purpose of taking a `np.maximum` with the 3-dimensional (x, y, z) normals map?

**Comment by woodfrog** [comment]
Hi @coldmanck , thanks for your interest in this work and let me try to answer your questions one by one:

1. **The intuition behind the usage of normals**.  First of all, I need to clarify that the data preprocessing scripts for Structured3D (your first snippet) come from the paper [MonteFloor](https://arxiv.org/abs/2103.11161), and I had included relevant information in the README file. The normals might not help corner detection, but since points on the same flat plane (e.g., wall, floor, ceiling) shares the same normal, the use of normals could benefit edge-level or room-level estimation. There is a visualization of the normal map in my earlier work [Floor-SP](https://openaccess.thecvf.com/content_ICCV_2019/papers/Chen_Floor-SP_Inverse_CAD_for_Floorplans_by_Sequential_Room-Wise_Shortest_Path_ICCV_2019_paper.pdf), see Figure 5 for the density+normal map. Note that Floor-SP and MonteFloor rely on room instance segmentation for further optimization, and normals can likely help this initial step.

2. **The first snippet**. For the choice of the sampling hyper-parameter, I believe it should depend on the data -- If you found that using ``10`` makes the density map too sparse and the structures less recognizable, you should decrease this value. The clipping into ``[0, 1]`` is indeed weird, and I cannot get the motivation behind this operation, or maybe it's a typo from the original author. 

3. **The second snippet**. The ``maximum`` operation is just my lazy trick to make sure that the combination of the density and normal map still has three channels and is a valid image so that the pre-trained ResNet can be directly used. There is no deep intuition behind it. You can also do a concatenation and add an extra linear projection to convert the input back to three channels.  

Hope it helps!
